title: Climate Change|Ankur Parikh|Advisement Project
author: GitHub User
email: ankurp08@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This site is about climate change. It was created for a school project.

# social links
github_username:  Potter25 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
